--TRANSAÇÕES
--BEGIN TRANSACTION OU SOMENTE BEGIN //SEPARA A TRANSAÇÃO SÓ PRA MIM
--FINALIZA COM COMMIT OU ROLLBACK //CONCLUI OU VOLTA ANTES DA ALTERAÇÃO

--SAVEPOINT //É UM "CHECKPOINT" ENTRE UM BEGIN TRANSACTION E UM COMMIT, EXEMPLO:
BEGIN;
	UPDATE banco SET nome = 'a' WHERE numero = 56
	
SAVEPOINT VOLTA_UM; --MARQUEI UM CHECKPOINT AQUI
	UPDATE banco SET nome = 'b' WHERE numero = 20
	
ROLLBACK TO VOLTA_UM; --VOLTO PARA MEU CHECKPOINT

COMMIT

--SOMENTE ALTEROU A PRIMEIRA LINHA, POIS NO MEIO EU CRIEI UM SAVEPOINT E TIVE QUE DAR UM ROLBACK
