--CRIANDO FUNÇÕES

--FUNÇÃO SIMPLES USANDO PLSQL
CREATE OR REPLACE FUNCTION func_somar (INTEGER, INTEGER) --CRIA FUNÇÃO E DEFINE OS PARAMETROS
--PARAMETROS DE CONFIGURAÇÃO DA FUNÇÃO
RETURNS INTEGER  --RETORNA UM INTEIRO
SECURITY DEFINER --VERIFICA AS PERMISSÕES DE USUÁRIO
--RETURNS NULL ON NULL INPUT --SE HOUVER UM VALOR NULL PREENCHIDO UM DOS VALORES NO PARAMETRO, RETORNA NULL
CALLED ON NULL INPUT --SE HOUVER UM VALOR NULL, ELE CONSIDERA CONTINUAR O CALCULO, SE USARMOS COALESCE, PODEMOS TRABALHAR MELHOR USANDO ESSA OPÇÃO
LANGUAGE SQL   --LINGUAGEM
AS $$  --INICIA FUNÇÃO
	--SELECT $1 + $2 --PARAMETRO DE EXECUÇÃO
	SELECT COALESCE ($1,0) + COALESCE($2,0) --POR BOA PRATICA USANDO COALESCE PARA VERIFICAR SE O PRIMEIRO VALOR FOR NULL, RETORNA 2 VALOR = 0
$$; --TERMINA FUNÇÃO

SELECT func_somar (1, NULL)