JOIN

INNER
TRAZ TUDO ENTRE AS DUAS TABELAS COM RELAÇÃO

FULL 
TRAZ TUDO, INCLUSIVE AS TABELAS QUE ESTÃO SEM RELAÇÃO COMO 'NULL'

LEFT (OUTER)
TRAZ TUDO DA TABELA DA ESQUERDA

RIGHT (OUTER)
TRAZ TUDO DA TABELA DA DIREITA

CROSS
TODOS OS DADOS DE UMA TABELA SÃO RELACIONADOS COM TODOS DADOS DE OUTRA TABLA E CRIA UMA MATRIZ COM TODOS OS DADOS 

